import './globals.css'
import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/app/api/auth/[...nextauth]/route'
import Navbar from '@/components/Navbar'
import NextAuthProvider from '@/providers/NextAuthProvider'
import ReduxProvider from '@/redux/ReduxProvider'

const prompt = Prompt({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  variable: "--font-prompt",
});


export const metadata: Metadata = {
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const nextAuthSession = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={prompt.className}>
      <ReduxProvider>
        <NextAuthProvider session={nextAuthSession}>
          <Navbar />
          {children}
        </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  )
  }	